<?php

namespace Kodo\DashboardBundle\Repository;
use Kodo\DashboardBundle\Entity\Sectionmenu;

/**
 * ItemmenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemmenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getItemsbySectionId(Sectionmenu $sectionmenu)
    {
        $em = $this->getEntityManager();
        $result = $em
            ->getRepository('KodoDashboardBundle:Itemmenu')
            ->findby(['sectionmenuId' => $sectionmenu]);
        return $result;
    }


}
