<?php

namespace Kodo\DashboardBundle\Repository;

/**
 * SectionmenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionmenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSectionmenus()
    {
        $em = $this->getEntityManager();
        $result = $em
            ->getRepository('KodoDashboardBundle:Sectionmenu')
            ->findBy([], ['position' => 'ASC']);
        return $result;
    }

}
